{
 "title": "Notification V3",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "route", "label": "route", "query": { "query": "label_values(route)" } }
  ]
 },
 "panels": [
  { "title": "Notification", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average Workflow Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "rate(notification_workflow_duration_sum[1m]) / rate(notification_workflow_duration_count[1m])",
     "legendFormat": "{{workflow_name}} {{status}}"
    }
   ]
  },
  {
   "title": "Slow Workflow ( > 150 ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum by (le, workflow_name) (rate(notification_workflow_duration_bucket[1m]))) > 150",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "rate(notification_workflow_duration_count[1m])",
     "legendFormat": "{{workflow_name}}"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "SUM(notification_workflow_duration_count{status=\"failed\"})/SUM(api_http_renotification_workflow_duration_countquest_duration_count)*100",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Most Handled Workflow",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "topk(5, sum by(workflow_name) (notification_workflow_duration_count))",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Api", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "rate(api_http_request_duration_sum{route=~\"$route\"}[1m]) / rate(api_http_request_duration_count{route=~\"$route\"}[1m])",
     "legendFormat": "{{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "targets": [
    {
     "expr": "sum by(method, route) (api_http_request_duration_count{route=~\"$route\"})",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by(method, code) (rate(api_http_request_duration_count{route=~\"$route\"}[1m]))",
     "legendFormat": "{{method}} {{route}} {{code}}"
    }
   ]
  },
  {
   "title": "Slow Request (> 200 ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(api_http_request_duration_bucket[5m])) >= 200",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "SUM(api_http_request_duration_count{code=~\"5.*\", route=~\"$route\"})/SUM(api_http_request_duration_count{route=~\"$route\"})*100",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}